### ISSUE TITLE
stdin breaks ffpb

### ISSUE THREAD

**Issue by couleurm** [clitic/ffpb-rs#2]
Hello, I'm looking to use ffpb-rs in my program,

My niche use-case is that ffmpeg is takes yuv4mpegpipe input from stdin from [VSPipe](https://www.vapoursynth.com/doc/gettingstarted.html#output-with-vspipe), and doing so break ffpb-rs. Instead of showing progress like you'd expect it'd silent and then dumps all of the stats in a single line and a single line of the progress bar, in a finished state.

![image](https://github.com/clitic/ffpb-rs/assets/82747632/580c74ef-729c-41a0-a0cd-aab13067b833)

I'm eventually gonna implement it in my program [here](https://github.com/couleur-tweak-tips/smoothie-rs/blob/main/src/render.rs) if it ever gets to work

I made a minimal reproduction of the bug (with two ffmpeg spawns, since ffmpeg can also output yuv4mpegpipe so you don't need to bother with installing VapourSynth) with a fork which you try for yourself here:

https://github.com/couleurm/ffpb-rs/commit/5e8c0090299b777503ce243960609c561c0e7053

**Comment by clitic** [comment]
I will look into that.

**Comment by clitic** [comment]
@couleurm Sorry for late response but I have written a workaround here https://github.com/clitic/ffpb-rs/commit/2bc3ad552e6e228d449f8c997d1f8fe06a8cb926. I hope you can understand the changes I made. I would not implement such functionality in this simple program. So, I am closing this issue. You can take reference from code and implement your logic for your use case.
